---
- name: Ensure git's dependencies are installed.
  yum: pkg={{ item }} state=installed
  with_items:
    - gettext-devel
    - expat-devel
    - curl-devel
    - zlib-devel
    - perl-devel
    - openssl-devel
    - subversion-perl

- name: Download git.
  get_url: >
    url=https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz
    dest={{ workspace }}

- name: Expand git archive.
  command: >
    tar -zxf {{ workspace }}/git-{{ git_version }}.tar.gz
    chdir={{ workspace }}
    creates={{ workspace }}/git-{{ git_version }}/README

- name: Check if git is installed.
  command: which git
  changed_when: false
  failed_when: false
  register: git_installed

- name: Build git.
  command: >
    make prefix={{ git_install_path }} {{ item }}
    chdir={{ workspace }}/git-{{ git_version }}
  when: "'no git' in git_installed.stdout"
  with_items:
    - all
    - install
  sudo: yes
